### ISSUE TITLE
Map not updated - Season 2 Chapter 4

### ISSUE THREAD

**Issue by tongclement** [Yogsther/fortnite-maps#4]
The map in the application is still one of the Season 1 ones. If I have time, I will contribute and update it. Any help is welcomed. Thanks so much :)

**Comment by tongclement** [comment]
Low quality map attached @Yogsther @Maxopoly @Teelair What are the requirements of the dimensions? Any calibration necessary? Any help is appreciated. Thanks very much.

![Uploading fortnite-mapa-temporada-4-chapter-2.jpg…]()

**Comment by Yogsther** [comment]
I won't be updating the maps, but If someone wants to and make a pull request, they are welcome to.
